### PR TITLE
Remove obsolete lists and unnecessary tests

### PR DESCRIPTION
**Pull request by fmarier**
Many of the lists have been now been removed from shavar and some of the tests are for features that we ended up not shipping or removing.

This should ensure that the end-to-end test is limited to the functionality that we support as well as the list addition/removal tests.

### CODE REVIEW

**Comment by groovecoder** [comment]
`mozilla.lists` values look right. I'm not sure about the `urlclassifier` changes though. Are the `urlclassifier.flash*` prefs removed because they're not used anymore?

**Comment by fmarier** [comment]
> Are the `urlclassifier.flash*` prefs removed because they're not used anymore?

I removed them because we don't actually need to customize them anymore in order to test them fully.

**Comment by groovecoder** [comment]
r+ from me then. Looks good for @rbillings to merge.

**Comment by rbillings** [comment]
Looks good, thanks

**Pull request merged**
